name: Deploy to GitHub Pages

# Only for main
on:
  push:
    branches: main
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # clone repo to vm
    - uses: actions/checkout@v2
    
      # ставим нужный SDK (можно использовать и более старые)
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true
        
      # генерируем статические файлы
    - name: Publish project
      run: dotnet publish Resume.csproj -c Release --output release --nologo
      
    - name: Uploading files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.4.1
      with:
        branch: gh-pages
        folder: release/wwwroot
